services:
  - type: web
    name: bokeh-app
    env: python
    buildCommand: ""
    startCommand: bokeh serve main.py --port $PORT --allow-websocket-origin=simbev_dashboard.onrender.com
    plan: free
